services:
  postgres:
    image: postgres:latest
    container_name: signal-watcher-postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      # Volumen para persistir los datos
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: